
# not implemented:
#load_model: none
#match_str: none

meta:
  group: B7
  pc_name: az16
policy:
  policy: PPO
  learning_rate: 3e-4
  learning_rate_10M: 1e-4
  learning_rate_20M: 5e-5
  total_steps_limit: 100000
  total_time_steps: 100000
  max_episode_steps: 1920
  ep_step_limit: 1920
  batch_size: 60
  n_epochs: 10
env:
  goal: pickup
  robot_orientation: vertical
  robot_control_mode: position
  cube_count: 4
  constant_cube_spawn: false
  repeat_worst_performances: false
  total_steps_between_interaction: 0
  obs_space:
    suction_on: false
    holding_cube: true
    joints: true
    rel_pos: true
    ef_height: false
    ef_speed: false
  action_space:
    suction_on: true
    joints: true
  reward:
    dist_reward_func: -12 * self.dist + 4
    reward_ef_vertical: true
    reward_ef_vertical_scale: 1.0
    reward_per_held_cube: 0.0
    reward_per_stacked_cube: 2.0
    reward_for_ef_ground_col: 0.0
    reward_for_cube_ground_col: 0.0
    reward_for_ef_below_target_z: -1.0
