
# not implemented:
#load_model: none
#match_str: none

meta:
  group: "C1"
  # pc_name is set by config.py
  pc_name: null

policy:
  # PPO | SAC | A2C | TD3 | DDPG | DQN - each have unique arguments and standard values
  # Only PPO works - the others end at 1000 ep steps...
  policy: "PPO"
  # MultiInputPolicy | CnnPolicy - does not work for dict observation space
  # policy_type: "MultiInputPolicy"
  learning_rate: 3e-4
  learning_rate_5M: 1e-4
  learning_rate_10M: 5e-5
  learning_rate_15M: 1e-5
  learning_rate_20M: 5e-6
  # not implemented:
  #learning_rates: "10M: 3e-4, 10M: 1e-4, 10M: 5e-5"
  total_steps_limit: 12_000
  total_time_steps: 12_000
  # 240 * 4 = 960, 240 * 8 = 1920, 240 * 12 = 2880, 240 * 16 = 3840
  max_episode_steps: 2880
  ep_step_limit: 2880
  batch_size: 60
  n_epochs: 10
  use_sde: false
  use_rms_prop: true

env:
  # reach | touch | pickup | stack
  goal: "stack"
  stack_start_with_cubes: false
  early_termination: true
  # vertical | horizontal
  robot_orientation: "horizontal"
  # position | velocity
  robot_control_mode: "position"
  cube_count: 4
  # not implemented:
  constant_cube_spawn: false
  repeat_worst_performances: false
  total_steps_between_interaction: 0
  use_absolute_pos: false
  # even if action_space.suction_on is disabled, include it in the action space for future training
  include_suction_on_action: true
  suction_release_automatic: true

  obs_space:
    suction_on: false
    holding_cube: true
    joints: false
    rel_pos: true
    ef_height: true
    ef_speed: false
  action_space:
    suction_on: true
    joints: true

  reward:
    # 0 | -12 * self.dist + 4 | minimise_xy_dist
    # 0 | -12 * self.dist + 4 | 0.1 / (self.dist + 0.05 / 2) | max(-12 * self.dist + 4, -60 * self.dist + 5)
    dist_reward_func: "-12 * self.dist + 4"
    # false: 0 | true: max(0, (self.ef_angle - 90) / 90) * reward_ef_vertical_scale
    reward_ef_vertical: true
    reward_ef_vertical_scale: 1
    reward_suction_control_scale: 2
    reward_per_held_cube: 8
    reward_per_stacked_cube: 10
    reward_for_ef_ground_col: -1
    reward_for_cube_ground_col: 0
    reward_for_ef_below_target_z: 0
    reward_for_suction_on_without_cube: -2
